name: ABAP CI (Trial OAuth keys: Clone + Pull + AUnit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  clone-and-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- CLONE (idempotent): creates/updates the BYOG repo in ABAP system and stores GitHub creds there ---
      - name: Clone BYOG repo into ABAP Environment (trial OAuth)
        uses: SAP/project-piper-action@v1.22.6
        with:
          step-name: abapEnvironmentCloneGitRepo
          # Pass the full service key JSON (OAuth) directly:
          flags: >
            --parametersJSON '${{ secrets.SC0948_SERVICE_KEY_JSON }}'
            --repositoryName "${{ secrets.SC_REPOSITORY_NAME }}"
            --branchName "${{ secrets.SC_BRANCH }}"
            --byogUsername "${{ secrets.BYOG_USERNAME }}"
            --byogPassword "${{ secrets.BYOG_TOKEN }}"

      # --- PULL latest commit (activation/compile happens in ABAP system on import) ---
      - name: Pull latest from Git (trial OAuth)
        uses: SAP/project-piper-action@v1.22.6
        with:
          step-name: abapEnvironmentPullGitRepo
          flags: >
            --parametersJSON '${{ secrets.SC0948_SERVICE_KEY_JSON }}'
            --repositoryName "${{ secrets.SC_REPOSITORY_NAME }}"
            --branchName "${{ secrets.SC_BRANCH }}"

  aunit:
    needs: clone-and-pull
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- Run ABAP Unit on your package (executed INSIDE the ABAP system) ---
      - name: Run ABAP Unit (trial OAuth)
        uses: SAP/project-piper-action@v1.22.6
        with:
          step-name: abapEnvironmentRunAUnitTest
          flags: >
            --parametersJSON '${{ secrets.SC0735_SERVICE_KEY_JSON }}'
            --abapPackage "${{ secrets.ABAP_PACKAGE }}"
