name: ABAP CI (Pull + AUnit via Piper Action)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  ABAP_PACKAGE: Z_YOUR_PACKAGE        # <-- change to your package
  ATC_VARIANT: DEFAULT                # (unused here; add later if you run ATC)

jobs:
  pull-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write ABAP service key
        run: echo '${{ secrets.ABAP_SERVICE_KEY_JSON }}' > service-key.json

      # === BUILD (ABAP-style): Pull repo into ABAP Env (activation happens in-system) ===
      - name: Pull sources into ABAP Environment
        uses: SAP/project-piper-action@v1.22.6
        with:
          step-name: abapEnvironmentPullGitRepo
          flags: >
            --serviceKey service-key.json
            --repositoryUrl "${{ secrets.ABAP_GIT_REPO_URL }}"
            --branchName   "${{ secrets.ABAP_GIT_BRANCH }}"

      # === TEST: Run ABAP Unit on your package ===
      - name: Run ABAP Unit tests
        uses: SAP/project-piper-action@v1.22.6
        with:
          step-name: abapEnvironmentRunAUnitTest
          flags: >
            --serviceKey service-key.json
            --abapPackage "${{ env.ABAP_PACKAGE }}"
